version: '3.4'
services:
 mongodb:
    image: mongo:4.0
    ports:
      - "27017:27017"
 tm:
    build: .
    depends_on:
      - mongodb
    ports:
      - "8089:8089"
    environment:
      - MONGODB_HOST=mongodb
